// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xopoawdcwslbolwnyywx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvcG9hd2Rjd3NsYm9sd255eXd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NjI4NDksImV4cCI6MjA1OTQzODg0OX0.fT-A56PAA9wxE-lPxB4RnvM3r-SggrblM6pnrraYkWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);